import React, { FC, ReactNode } from "react";
import Head from "next/head";
import styles from "../styles/components/layout.module.scss";
import Link from "next/link";
import classNames from "classnames";
import { Button } from "@mui/material";

interface LayoutProps {
  title: string | undefined;
  children: ReactNode;
}

export const Layout: FC<LayoutProps> = ({ title, children }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className="container">
          <div className={styles.inner}>
            <Link href="/">
              <a className={styles.header_logo}>Logo</a>
            </Link>
            <Button
              className={styles.header_btn}
              variant="text"
              color="primary"
            >
              Kirish
            </Button>
          </div>
        </div>
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={classNames(styles.footer, "container")}>
        <p className={styles.text}>Copyright ©2022 All rights reserved</p>
      </footer>
    </div>
  );
};
